# Generated by Django 6.1.1 on 2026-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
